language: ruby
sudo: false
addons:
  apt:
    packages:
    - bind9
rvm:
  - 2.2.6
  - 2.3.3
  - 2.4.0
  - rbx-2
  - ruby-head
  - jruby-head
matrix:
  allow_failures:
    - rvm: rbx-2 
    - rvm: ruby-head
    - rvm: jruby-head