language: ruby
sudo: false
dist: trusty
cache: bundler
addons:
  apt:
    packages:
    - bind9

before_script: sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'

matrix:
  include:
    - rvm: 2.3
    - rvm: 2.4
    - rvm: 2.5
    - rvm: ruby-head
    - rvm: jruby-head
      env:
        - JRUBY_OPTS="--debug -X+O"
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
